title: Ameya Dattaram Parab
#logo:
description: Data Science Graduate Student at Indiana University Bloomington
theme: jekyll-theme-minimal

periods:
  - events:
    - October 1990: "ðŸ‘¶ Neil is born in Michigan."
    - December 1990: "âœˆï¸ Neil moves to California."
    - August 1994: "ðŸ‘¶ Neil's sister, Nandini, is born."
    - February 1995: "ðŸ’© Neil splatters poop on his walls while swinging a garbage bag with a dirty diaper. This is his first physics lesson."
    - December 1997: "ðŸ  Neil moves to a new home on Christmas. It's 100% less shitty than the last one."
    - July 1998: "ðŸŽ¬ Neil directs his first action movie using a VHS camcorder and PowerMac 8500."
    - March 1999: "ðŸ•¶ The Matrix is released. Neil has to clarify his name isn't Neo for the rest of the decade."
    - June 1999: "ðŸ”¥ Neil's internet connection is upgraded from dial-up to 6mbps DSL. He starts tinkering with web development. And Napster."
  - name: 2000's
    events:
    - October 2000: "ðŸŽ‚ Neil turns 10. It's a new millennium."
    - August 2002: "ðŸŽ“ Neil starts middle school."
    - August 2002: "ðŸ§® Neil gets a TI-83 Plus Silver Edition calculator that he uses to program games in BASIC during class."
    - September 2002: "ðŸ¹ Neil earns his Arrow of Light, graduating from a Cub Scout to Boy Scout."
    - July 2004: "ðŸ‘¨â€ðŸ’» Neil launches WebScope.tv, a video sharing platform for his friends because YouTube doesn't exist yet."
    - August 2004: "ðŸŽ“ Neil starts high school."
    - December 2005: "ðŸ‘¨â€ðŸ’» Neil cofounds Amalgam, an online literary magazine, and builds a NoSQL CMS to power it."
    - September 2006: "ðŸ‘¨â€ðŸ’» Neil cofounds Metamorphium Design, a profitable web design business."
    - May 2007: "ðŸ‘¨â€ðŸ’» Neil joins a sports social network as developer #1. He works out of a literal garage in Silicon Valley."
    - August 2007: "ðŸ“± Neil gets the first iPhone. People make fun of him for spending $600 on a phone."
    - August 2008: "âœˆï¸ Neil moves to Chicago."
    - November 2009: >-
        ðŸ“· Neil gets a DSLR camera and picks up <a href="https://photos.neil.gg" target="_blank" rel="noopener"
        title="See some of my photos">photography as a hobby</a>.

